services:
  - type: web
    name: aagontuk
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
